version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "next"
          - "react"
          - "react-dom"
          - "eslint"
          - "eslint-config-next"
          - "typescript"
