import type { Metadata } from "next";

import { SITE_URL } from "@/lib/site-url";

export const metadata: Metadata = {
  title: {
    absolute: "Terms of Service | MedCalcHub",
  },
  description:
    "Terms of Service for MedCalcHub — conditions of use for the medical calculator platform.",
  alternates: {
    canonical: `${SITE_URL}/terms`,
  },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-10">
      <h1 className="text-3xl font-bold">Terms of Service</h1>

      <p className="mt-2 text-sm text-amber-700 dark:text-amber-400 font-semibold">
        Legal review required before production use.
      </p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-slate-700 dark:text-slate-300">
        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using MedCalcHub (the &quot;Platform&quot;), you
            agree to be bound by these Terms of Service. If you do not agree to
            these terms, do not use the Platform.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            2. Nature of the Platform
          </h2>
          <p>
            MedCalcHub is a clinical decision-support tool that provides
            medical calculators and scoring systems for use by qualified
            healthcare professionals. The Platform is provided for informational
            and educational purposes.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            3. No Medical Diagnosis or Treatment
          </h2>
          <p>
            <strong>
              MedCalcHub does not provide medical advice, diagnosis, or
              treatment.
            </strong>{" "}
            The calculators and scoring systems on this Platform are tools that
            assist qualified healthcare professionals in applying published
            clinical formulas. They do not replace professional clinical
            judgment, and no result generated by the Platform should be used as
            the sole basis for any medical decision.
          </p>
          <p className="mt-2">
            Users are solely responsible for interpreting results in the context
            of the individual patient&apos;s clinical presentation and for making
            all clinical decisions based on their own professional judgment.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            4. Intended Users
          </h2>
          <p>
            MedCalcHub is intended for use by qualified healthcare
            professionals. It is not intended for patients, consumers, or
            members of the general public as a substitute for professional
            medical advice.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            5. Calculator Limitations
          </h2>
          <p>
            Calculators on the Platform have inherent limitations, including but
            not limited to:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1">
            <li>
              Results depend on the accuracy of user-entered inputs.
            </li>
            <li>
              Published formulas were validated for specific populations and may
              not be appropriate for all patient groups.
            </li>
            <li>
              Calculators do not account for all clinical variables, comorbidities,
              or individual patient factors.
            </li>
            <li>
              Results are estimates or classifications, not definitive clinical
              endpoints.
            </li>
            <li>
              Calculator content, including interpretation ranges and clinical
              notes, may not reflect the most current clinical evidence.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            6. User Responsibilities
          </h2>
          <p>Users agree to:</p>
          <ul className="mt-2 list-inside list-disc space-y-1">
            <li>
              Use the Platform only for lawful purposes and in accordance with
              these terms.
            </li>
            <li>
              Verify the accuracy of all inputs before interpreting results.
            </li>
            <li>
              Apply professional clinical judgment to all results.
            </li>
            <li>
              Not rely on the Platform as the sole basis for clinical decisions.
            </li>
            <li>
              Not enter personally identifiable patient information into the
              Platform.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            7. Acceptable Use
          </h2>
          <p>
            Users must not attempt to disrupt, reverse-engineer, or compromise
            the Platform; introduce malicious code; use automated systems to
            extract content without permission; or use the Platform in any way
            that could cause harm or violate applicable laws.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            8. Intellectual Property
          </h2>
          <p>
            The Platform, including its calculators, clinical content, design,
            and code, is protected by applicable intellectual property laws.
            The open-source components of the Platform are licensed under the
            terms specified in the project&apos;s public repository.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            9. Disclaimers
          </h2>
          <p>
            <strong>
              The Platform is provided &quot;as is&quot; and &quot;as
              available&quot; without warranties of any kind, whether express
              or implied, including but not limited to implied warranties of
              merchantability, fitness for a particular purpose, and
              non-infringement.
            </strong>
          </p>
          <p className="mt-2">
            We do not warrant that the Platform will be uninterrupted, error-free,
            or free of harmful components. We do not warrant the accuracy,
            completeness, or reliability of any calculator output or clinical
            content.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            10. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by applicable law, the operators of
            MedCalcHub shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of profits or
            revenues, whether incurred directly or indirectly, or any loss of
            data, use, goodwill, or other intangible losses resulting from:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1">
            <li>Your use of or inability to use the Platform.</li>
            <li>
              Any errors or omissions in any calculator output or content.
            </li>
            <li>
              Any clinical decisions made based on results from the Platform.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            11. Privacy and Cookies
          </h2>
          <p>
            Your use of the Platform is also governed by our{" "}
            <a
              href="/privacy"
              className="underline hover:text-blue-600 dark:hover:text-blue-400"
            >
              Privacy Policy
            </a>{" "}
            and{" "}
            <a
              href="/cookie"
              className="underline hover:text-blue-600 dark:hover:text-blue-400"
            >
              Cookie Policy
            </a>
            , which are incorporated into these terms by reference.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            12. Changes to These Terms
          </h2>
          <p>
            We reserve the right to modify these Terms of Service at any time.
            Changes will be posted on this page with an updated revision date.
            Your continued use of the Platform after any changes constitutes
            acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-slate-100">
            13. Contact
          </h2>
          <p>
            If you have questions about these Terms of Service, please see the{" "}
            <a
              href="/contact"
              className="underline hover:text-blue-600 dark:hover:text-blue-400"
            >
              Contact page
            </a>{" "}
            for how to reach us.
          </p>
        </section>
      </div>
    </div>
  );
}
